base:
  proxy: ""
media:
  library: emby
  url: ""
  api: ""
  secretid: ""
  secretkey: ""
path:
  success: success
  fail: fail
  directory: '{actor}/{year}/{number}'
  filter: -hd||hd-||_hd||hd_||[||]||【||】||asfur||~||-full||_full||3xplanet||monv||云中飘荡||@||tyhg999.com||xxxxxxxx||-fhd||_fhd||thz.la
site:
  javbus: https://www.javbus.com/
  javdb: https://javdb4.com/
